AY2425S1-CS2103T-W08-2/tp

docs/AboutUs.md
=> Update AboutUs page for Amitha

docs/AboutUs.md
=> Update AboutUs page for Jiehui

docs/DeveloperGuide.md
=> Update dev guide user stories

docs/DeveloperGuide.md
=> Update NFR and Glossary in DG

docs/DeveloperGuide.md
=> Add second half of use cases into developers' guide

docs/DeveloperGuide.md
=> Add first half of use cases in Developer's Guide

README.md
=> Add Java CI status and codecov badge to README

src/main/java/seedu/address/model/person/Attendance.java
=> Add new Attendance class to model

src/main/java/seedu/address/model/person/Payment.java
=> Create payment class under person

src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/MarkAttendanceCommandParser.java
Add new MarkAttendanceCommand and MarkAttendanceParser class.
Edit AddressBookParser to check for command "markattend".
closes #51
=> Add mark attendance feature

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java, src/main/java/seedu/address/logic/commands/MarkPaidCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/Payment.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/main/java/seedu/address/ui/PersonCard.java, src/main/resources/view/PersonListCard.fxml, src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/parser/AddCommandParserTest.java, src/test/java/seedu/address/model/person/PersonTest.java, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java, src/test/java/seedu/address/testutil/PersonBuilder.java, src/test/java/seedu/address/testutil/PersonUtil.java
fixes #47 #48 #49 
Change constructor of person class
Update AddCommandParser
Update EditCommand
Update Storage
Update UI
Update relevant tests to the above class
Will contain test coverage for person class in next few commits
=> V1.3 Add payment field to person

src/main/java/seedu/address/logic/commands/FilterPaidCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/FilterPaidCommandParser.java, src/main/java/seedu/address/model/person/StudentHasPaidPredicate.java, src/test/java/seedu/address/logic/commands/FilterPaidCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/FilterPaidCommandParserTest.java, src/test/java/seedu/address/model/person/StudentHasPaidPredicateTest.java, src/test/java/seedu/address/testutil/PersonBuilder.java
Closes #50
Adds FilterPaidCommand, parser and associated tests.
Updates the StudentHasPaidPredicate to support Payment class.
Updates PersonBuilder with Payment.
=> Add filter payment

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java, src/main/java/seedu/address/logic/commands/MarkPaidCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/Attendance.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/main/java/seedu/address/ui/HelpWindow.java, src/main/java/seedu/address/ui/PersonCard.java, src/main/resources/view/MainWindow.fxml, src/main/resources/view/PersonListCard.fxml, src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java, src/test/java/seedu/address/logic/parser/AddCommandParserTest.java, src/test/java/seedu/address/model/person/PersonTest.java, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java, src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java, src/test/java/seedu/address/testutil/PersonBuilder.java, src/test/java/seedu/address/testutil/PersonUtil.java, src/test/java/seedu/address/testutil/TypicalPersons.java
Fixes #60,#61, #62
Add a new Attendance class.
Add an Attendance field to the Person class.
Update JsonAdaptedPerson class to support serialisation and deserialisation with the new Attendance field.
Update existing commands to support the new Attendance field in Person class.
Update parsers to recognise Attendance prefix.
Fix test cases.
Include some minor fixes for UI display.
=> Integrate Attendance field to Person class and other classes

src/test/java/seedu/address/testutil/PersonBuilder.java
Closes #76 
Chose the boolean variable name to follow variable naming for booleans.
=> Personbuilder duplicate code

src/main/java/seedu/address/model/person/Attendance.java, src/test/java/seedu/address/model/person/AttendanceTest.java, src/test/java/seedu/address/util/SampleDataUtilTest.java
=> Attendance feature: Add test cases

docs/UserGuide.md
=> Update User Guide Filter Payment

src/main/java/seedu/address/logic/commands/MarkPaidCommand.java, src/test/java/seedu/address/logic/commands/MarkPaidCommandTest.java
=> Add test cases for MarkPaidCommand

docs/UserGuide.md
=> Edit user guide to include markpaid

src/main/java/seedu/address/model/Participation.java, src/main/java/seedu/address/model/Tutorial.java, src/main/java/seedu/address/model/tutorial/Tutorial.java
=> Add tutorial and participation classes

src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/ReadOnlyAddressBook.java, src/main/java/seedu/address/model/tutorial/UniqueTutorialList.java, src/main/java/seedu/address/model/tutorial/exceptions/DuplicateTutorialException.java, src/main/java/seedu/address/model/tutorial/exceptions/TutorialNotFoundException.java, src/main/java/seedu/address/storage/JsonAdaptedTutorial.java, src/main/java/seedu/address/storage/JsonSerializableAddressBook.java, src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/duplicateTutorialAddressBook.json, src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/java/seedu/address/model/AddressBookTest.java, src/test/java/seedu/address/model/tutorial/UniqueTutorialListTest.java, src/test/java/seedu/address/storage/JsonAdaptedTutorialTest.java, src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java, src/test/java/seedu/address/testutil/TutorialBuilder.java, src/test/java/seedu/address/testutil/TypicalPersons.java
Closes #92 and #96 
Adds tutorial field to addressbook json. Extra class created to support this.
Adjusted relevant cases to support new field.
=> Add Tutorial json storage

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/ClearCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/Attendance.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/main/java/seedu/address/ui/PersonCard.java, src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/MarkAttendanceCommandTest.java, src/test/java/seedu/address/model/person/AttendanceTest.java, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java, src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java, src/test/java/seedu/address/testutil/PersonBuilder.java, src/test/java/seedu/address/testutil/PersonUtil.java, src/test/java/seedu/address/testutil/TypicalPersons.java, src/test/java/seedu/address/util/SampleDataUtilTest.java
closes #97 
1. Change Attendance class to contain Date field instead of Boolean
2. Update test cases
=> Update Attendance class to indicate date attended

src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/model/participation/Participation.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java
=> Replace Attendance with List<Participation> in Person

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/CreateTutorialCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/CreateTutorialCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/person/Name.java, src/main/java/seedu/address/model/tutorial/Tutorial.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java
**Main changes:**
New command: createtut tut/TUT_NAME
- createtut creates a new tutorial object with an empty participation list.
- Does not allow duplicate prefix.
- Does not allow inputs before the tut/ prefix other than createtut command.
**Minor changes:**
Change prefix name.
Update messages returned to users.
Remove JsonProperty Tag from storage.
**Note:**
Test cases are not updated yet.
Some Javadocs are not updated yet.
=> Add a command to create tutorial

src/main/java/seedu/address/logic/commands/MarkPaidCommand.java, src/main/java/seedu/address/model/person/Person.java
1. Changes fields in Person to be mutable
2. Changes MarkPaidCommand to edit Person object directly
=> Edit fields in Person to be mutable and edit MarkPaidCommand accordingly

src/main/java/seedu/address/logic/commands/MarkAttendanceByStudentCommand.java, src/main/java/seedu/address/logic/commands/MarkAttendanceByTutorialCommand.java, src/test/java/seedu/address/logic/commands/MarkAttendanceByTutorialCommandTest.java, src/test/java/seedu/address/logic/parser/MarkAttendanceByStudentCommandParserTest.java, src/test/java/seedu/address/logic/parser/MarkAttendanceByTutorialCommandParserTest.java
1. Update test cases to compile
2. Use mutable list to mark attendance
=> Minor changes to mark attendance of student command

src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
=> Fix JsonAdaptedPersonTest

src/test/java/seedu/address/model/person/PersonTest.java, src/test/java/seedu/address/model/tutorial/TutorialTest.java
Fix PersonTest to reflect new isSamePerson equality (Name and Phone)
Fix Tutorial test to use getCanonicalName
=> Fix test cases

docs/diagrams/StorageClassDiagram.puml
=> Update Storage uml

src/main/java/seedu/address/logic/commands/EnrollCommand.java, src/main/java/seedu/address/logic/commands/UnEnrollCommand.java
fixes #159 
- Remove dependencies between enroll/unenroll to particiaptionList under person and tutorial
- Update the Messages to be neater in GUI
=> V1.5 enroll commands

src/main/java/seedu/address/logic/commands/DeleteCommand.java
=> Update DeleteCommand to change participation list

src/main/java/seedu/address/logic/commands/MarkPaidCommand.java
=> Update MarkPaid command to create new Participation objects

src/main/java/seedu/address/logic/commands/EditCommand.java
=> Update EditCommand to make new Participation objects

src/main/java/seedu/address/storage/JsonSerializableAddressBook.java, src/test/data/JsonSerializableAddressBookTest/duplicateParticipationAddressBook.json, src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/duplicateTutorialAddressBook.json, src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/nullParticipationAddressBook.json, src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/java/seedu/address/storage/JsonAdaptedAttendanceTest.java, src/test/java/seedu/address/storage/JsonAdaptedParticipationTest.java, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java, src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java, src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java, src/test/java/seedu/address/testutil/TypicalPersons.java
Added a Participation to TypicalPersons.
Added test cases to cover the storage in json format.
Closes #182
=> Add Json Test Cases

src/main/java/seedu/address/storage/JsonAdaptedParticipation.java, src/test/data/JsonSerializableAddressBookTest/duplicateParticipationAddressBook.json, src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/java/seedu/address/storage/JsonAdaptedParticipationTest.java
=> Add phone field to storage to check for duplicate Persons

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/MarkPaidCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/model/participation/Participation.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/tutorial/Tutorial.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/test/java/seedu/address/model/person/PersonTest.java, src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java, src/test/java/seedu/address/testutil/PersonBuilder.java
=> Remove ParticipationList from Person Tutorial

docs/UserGuide.md
Filterp is gone, so remove the user guide for it.
=> Remove filterp from user guide

src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/Person.java, src/test/java/seedu/address/model/person/PersonTest.java
Closes #199 
1. Checks for multiple whitespaces between different parts of a name and replaces with single whitespace
2. Checking for duplicate names is now case insensitive
=> Fix bugs of adding duplicate people for Add command

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/MarkPaidCommand.java
=> Remove attendance from add command error message

src/main/java/seedu/address/logic/commands/MarkAttendanceByStudentCommand.java, src/main/java/seedu/address/model/person/Attendance.java, src/test/java/seedu/address/logic/commands/MarkAttendanceByStudentCommandTest.java, src/test/java/seedu/address/logic/commands/MarkAttendanceByTutorialCommandTest.java, src/test/java/seedu/address/logic/parser/MarkAttendanceByStudentCommandParserTest.java, src/test/java/seedu/address/logic/parser/MarkAttendanceByTutorialCommandParserTest.java, src/test/java/seedu/address/logic/parser/UnmarkAttendanceByStudentCommandParserTest.java, src/test/java/seedu/address/model/person/AttendanceTest.java, src/test/java/seedu/address/storage/JsonAdaptedParticipationTest.java, src/test/java/seedu/address/testutil/TypicalPersons.java
=> Update mark attendance to prevent marking future date

src/main/java/seedu/address/logic/commands/AddCommand.java
Add command invalid input spacing
=> Add spacing to help message

src/main/java/seedu/address/storage/JsonAdaptedParticipation.java
=> Fix bug with duplicate attendance

docs/DeveloperGuide.md, docs/UserGuide.md, src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/AddFeesCommand.java, src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/EnrollCommand.java, src/main/java/seedu/address/logic/commands/FindCommand.java, src/main/java/seedu/address/logic/commands/ListCommand.java, src/main/java/seedu/address/logic/commands/MarkAttendanceByStudentCommand.java, src/main/java/seedu/address/logic/commands/MarkPaidCommand.java, src/main/java/seedu/address/logic/commands/UnmarkAttendanceByStudentCommand.java, src/test/java/seedu/address/logic/commands/FindCommandTest.java
=> Bug fix: Remove check that disallows marking of payment after unenrolling
